# Generated by Django 4.2.9 on 2025-09-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('bio', models.TextField()),
                ('video', models.ImageField(upload_to='home/')),
                ('projects_link', models.URLField()),
            ],
        ),
    ]
