# Generated by Django 4.2.9 on 2025-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='home/'),
        ),
    ]
