# Generated by Django 4.2.9 on 2025-08-14 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact_info',
            new_name='ContactInfo',
        ),
    ]
