# Generated by Django 4.2.9 on 2025-10-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
